name: Question ?
description: Ask a question, start a discussion , share an idea or need help ?
labels: ["question"]
body:
  - type: markdown
    attributes:
      value: |
        Before to ask a question : 
         - Try to search if question is not already answered in [previous issue](https://github.com/eclipse/leshan/issues).
         - Look at the [F.A.Q.](https://github.com/eclipse/leshan/wiki/F.A.Q.).
         - Look at the [documentation](https://github.com/eclipse/leshan/wiki).

  - type: textarea
    id: question
    attributes:
      label: "Question"
      description: |
         (Please do not use screenshot to share textual information)
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        If you're using Leshan [let us know](https://github.com/eclipse/leshan/issues/830) and/or star the project ⭐.
